// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Zf689v9Lqp1zw1srAtMIHGrCgP6tZwg',
    appId: '1:26977788191:web:c5bc97976e771e762cd02a',
    messagingSenderId: '26977788191',
    projectId: 'assamapp-35a89',
    authDomain: 'assamapp-35a89.firebaseapp.com',
    storageBucket: 'assamapp-35a89.firebasestorage.app',
    measurementId: 'G-XJ7TEP20CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpOlh6bvhfqGPqTS3nbwG2HmDiyVu_Ck',
    appId: '1:26977788191:android:eb4b38291721497f2cd02a',
    messagingSenderId: '26977788191',
    projectId: 'assamapp-35a89',
    storageBucket: 'assamapp-35a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSIeHOnsFMGKoOg7lGPflWQk_PzGKRcQ0',
    appId: '1:26977788191:ios:88d65cffad7369422cd02a',
    messagingSenderId: '26977788191',
    projectId: 'assamapp-35a89',
    storageBucket: 'assamapp-35a89.firebasestorage.app',
    iosBundleId: 'com.example.endgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSIeHOnsFMGKoOg7lGPflWQk_PzGKRcQ0',
    appId: '1:26977788191:ios:88d65cffad7369422cd02a',
    messagingSenderId: '26977788191',
    projectId: 'assamapp-35a89',
    storageBucket: 'assamapp-35a89.firebasestorage.app',
    iosBundleId: 'com.example.endgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Zf689v9Lqp1zw1srAtMIHGrCgP6tZwg',
    appId: '1:26977788191:web:7685ed8fde1d72292cd02a',
    messagingSenderId: '26977788191',
    projectId: 'assamapp-35a89',
    authDomain: 'assamapp-35a89.firebaseapp.com',
    storageBucket: 'assamapp-35a89.firebasestorage.app',
    measurementId: 'G-TMH9VEZL9L',
  );
}
